GET http://localhost:5000/api/orders

###

GET http://localhost:5000/api/orders/5e769794c68b82e96fe26c4e

###

POST http://localhost:5000/api/orders
Content-Type: application/json

{
  "items":[
    {
      "product": "5e778288b177e23969941eb2",
      "amount": "3"
    },
    {
      "product": "5e7782efb177e23969941eb4",
      "amount": "5"
    }
  ],
  "store": "5e778272b177e23969941eb1" 
}

###

DELETE http://localhost:5000/api/orders/5e7645e767add529c44d308b9ed99867e7cd639c4a36b7ec
