GET http://localhost:5000/api/stores
###

GET http://localhost:5000/api/stores/radius?latitude=235.5&longitude=43.3&distance=4.3

{
  "latitude": 47.9959,
  "longitude": 7.85222,
  "distance": 300
}

###

GET http://localhost:5000/api/stores/5e7637033530e88ed953fd1c/products

###

DELETE http://localhost:5000/api/stores/5e7637033530e88ed953fd1c/products/5e7660751a3f5eb1b025075c

###

GET http://localhost:5000/api/stores/5e7637033530e88ed953fd1c

###

POST http://localhost:5000/api/stores
Content-Type: application/json

{
  "name": "Bioladen Rübezahl - Südstadt",
  "vendor": "5e7781fbc3f1c40004c7e5f3",
  "latitude": "52.481659",
  "longitude": "10.575843"
}

###

DELETE http://localhost:5000/api/stores/5e764c0be18e3fa11b445c15


###

PATCH http://localhost:5000/api/stores/5e7785c3b177e23969941ecf
Content-Type: application/json

{
  "currentlyOpen" : true,
  "openingHours": [
    {"day": "monday", "from": "12", "to": "16"},
    {"day": "tuesday", "from": "9", "to": "16"},
    {"day": "wednesday", "from": "8", "to": "12"},
    {"day": "thursday", "from": "8", "to": "12"},
    {"day": "saturday", "from": "8", "to": "16"}
  ]
}

###

PATCH http://localhost:5000/api/stores/5e7637033530e88ed953fd1c/products/5e7660751a3f5eb1b025075d
Content-Type: application/json

{
      "name": "Gelber Spargel"
}

###

PATCH http://localhost:5000/api/stores/5e7785c3b177e23969941ecf/products
Content-Type: application/json

{
      "name": "Schale Erdbeeren",
      "type": "Erdbeere",
      "unit": "250g",
      "price": "250",
      "stock": "full",
      "imageUrl": "https://images.pexels.com/photos/583840/pexels-photo-583840.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" 
}

###
PATCH http://localhost:5000/api/stores/5e7785c3b177e23969941ecf/products
Content-Type: application/json

{
      "name": "Weißer Spargel",
      "type": "Spargel",
      "unit": "1 Bund 500g",
      "price": "700",
      "stock": "full",
      "imageUrl": "https://images.pexels.com/photos/351679/pexels-photo-351679.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" 
}

###
PATCH http://localhost:5000/api/stores/5e7785c3b177e23969941ecf/products
Content-Type: application/json

{
      "name": "Grüner Spargel",
      "type": "Spargel",
      "unit": "1 Bund 500g",
      "price": "800",
      "stock": "full",
      "imageUrl": "https://images.pexels.com/photos/351679/pexels-photo-351679.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" 
}

###
PATCH http://localhost:5000/api/stores/5e778446b177e23969941ebd/products
Content-Type: application/json

{
      "name": "Palette Erdbeeren",
      "type": "Erdbeere",
      "unit": "2 KG",
      "price": "1000",
      "stock": "full",
      "imageUrl": "https://images.pexels.com/photos/351679/pexels-photo-351679.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" 
}