
GET http://localhost:5000/api/vendors/5e778e6bdd5943000467a0df
authorization: Bearer _-dZageSHloOWS9gPu7TNhfO3rAax-55
###

POST http://rkg-api-602.herokuapp.com/api/vendors/signup
Content-Type: application/json


{
  "name": "Robert Huber",
  "email": "r.huber@example.com"
}

###

DELETE http://localhost:5000/api/vendors/5e761ba5385b4a71b6b9f295


###

PATCH http://localhost:5000/api/vendors/5e778e6bdd5943000467a0df
Content-Type: application/json
authorization: Bearer _-dZageSHloOWS9gPu7TNhfO3rAax-55

{
  "name": "Super Duper"
}