GET http://localhost:5000/vendors

###

GET http://localhost:5000/vendors/5e761ba5385b4a71b6b9f295

###

POST http://localhost:5000/vendor
Content-Type: application/json

{
  "name": "Robert Huber",
  "email": "r.huber@example.com"
}