GET http://localhost:5000/api/authtest
authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik5FWkNRelExTlRFMk16ZzBRemM0TXpaRU9UQTNRVU0wUlRJMFFqVTBRems0UVRWRU9Ea3lSUSJ9.eyJpc3MiOiJodHRwczovL3JrZy5ldS5hdXRoMC5jb20vIiwic3ViIjoidmt1Uktic2VpVzdxR2hHSjRSaTNCaHFtcGJlaTh5SUFAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vcmtnLWFwaSIsImlhdCI6MTU4NDg2NzUwOSwiZXhwIjoxNTg0OTUzOTA5LCJhenAiOiJ2a3VSS2JzZWlXN3FHaEdKNFJpM0JocW1wYmVpOHlJQSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.DpFYcQEnmvl49TZxV8JFgND2yo6TSX2k4pwDG34zus9enChzk0QhLthIbXfpWRO7TV6QpH3Xlgb4WL6KVDTc6QsYvjOq5T2sJTNYw9a2oBsPqun6cpbhoh_4t0MKRZXBHXj_mG345XefS8bXQifHouQ68qRm6Jb2giynRPmNo-yMx5ApinrJjwV_bxtQmn77lsgsEYVmbPAqIlqToW57RJ4S_8StzUUtVaLQAFThHnlY2itRzl_widSDdwzojsLTlwx1PSZApEqBfzONl5zkzi6GR-JDzOoeU2fiSO-VyHTWVKEewbt5Xn4C2WkV2RngH-E1kqSs6y35dVmCzVPnHg

###

GET http://localhost:5000/api/userprofile
authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik5FWkNRelExTlRFMk16ZzBRemM0TXpaRU9UQTNRVU0wUlRJMFFqVTBRems0UVRWRU9Ea3lSUSJ9.eyJpc3MiOiJodHRwczovL3JrZy5ldS5hdXRoMC5jb20vIiwic3ViIjoidmt1Uktic2VpVzdxR2hHSjRSaTNCaHFtcGJlaTh5SUFAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vcmtnLWFwaSIsImlhdCI6MTU4NDg2NzUwOSwiZXhwIjoxNTg0OTUzOTA5LCJhenAiOiJ2a3VSS2JzZWlXN3FHaEdKNFJpM0JocW1wYmVpOHlJQSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.DpFYcQEnmvl49TZxV8JFgND2yo6TSX2k4pwDG34zus9enChzk0QhLthIbXfpWRO7TV6QpH3Xlgb4WL6KVDTc6QsYvjOq5T2sJTNYw9a2oBsPqun6cpbhoh_4t0MKRZXBHXj_mG345XefS8bXQifHouQ68qRm6Jb2giynRPmNo-yMx5ApinrJjwV_bxtQmn77lsgsEYVmbPAqIlqToW57RJ4S_8StzUUtVaLQAFThHnlY2itRzl_widSDdwzojsLTlwx1PSZApEqBfzONl5zkzi6GR-JDzOoeU2fiSO-VyHTWVKEewbt5Xn4C2WkV2RngH-E1kqSs6y35dVmCzVPnHg
