GET http://localhost:5000/api/products
###

GET http://localhost:5000/api/products/5e7627ebe87c1a7af2f09758

###

POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "Erdbeeren",
  "type": "Erdbeere",
  "unit": "500g",
  "price": "250",
  "stock": "full"
}


###

DELETE http://localhost:5000/api/products/5e761ba5385b4a71b6b9f295


###

PATCH http://localhost:5000/api/products/5e761984ebd80d6f7c8d4990
Content-Type: application/json

{
  "name": "Erdbeeren",
  "type": "Frucht",
  "amount": "250g",
  "price": 150,
  "stock": "none",
}