GET http://localhost:5000/api/orders

###

GET http://localhost:5000/api/orders/5e7637033530e88ed953fd1c

###

POST http://localhost:5000/api/orders
Content-Type: application/json

{
  "items":[
    {
      "product": "5e7660751a3f5eb1b025075d",
      "amount": "10"
    },
    {
      "product": "5e7670c0e35d55c5893fb783",
      "amount": "5"
    }
  ],
  "store": "5e7637033530e88ed953fd1c" 
}

###

DELETE http://localhost:5000/api/orders/5e7645e767add529c44d308b9ed99867e7cd639c4a36b7ec
